# Generated by Django 5.1.6 on 2026-02-21 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameroom',
            name='server_connect_url',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AddField(
            model_name='gameroom',
            name='server_error',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='gameroom',
            name='server_host',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='gameroom',
            name='server_launch_command',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AddField(
            model_name='gameroom',
            name='server_password',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='gameroom',
            name='server_port',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gameroom',
            name='server_provider_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='gameroom',
            name='server_provisioned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
