from django.urls import path
from rest_framework_simplejwt.views import TokenRefreshView

from .views import (
    AllowedInvitersView,
    ChatDialogsView,
    ChatMessagesView,
    DeleteAccountConfirmView,
    DeleteAccountRequestView,
    FriendRequestAcceptView,
    FriendRequestCreateView,
    FriendRequestDeclineView,
    FriendRequestsIncomingView,
    FriendsListView,
    LoginView,
    NotificationMarkAllReadView,
    NotificationMarkReadView,
    NotificationsListView,
    PasswordChangeView,
    PasswordResetConfirmView,
    PasswordResetRequestView,
    ProfileView,
    PublicProfileView,
    RegisterView,
    TelegramLinkCodeView,
    TelegramNotificationsToggleView,
    UserSearchView,
    VerifyEmailAPIView,
    telegram_link_callback,
)

urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', LoginView.as_view(), name='login'),
    path('token/refresh/', TokenRefreshView.as_view(), name='token-refresh'),
    path('verify-email/', VerifyEmailAPIView.as_view(), name='verify-email'),
    path('password-reset/request/', PasswordResetRequestView.as_view(), name='password-reset-request'),
    path('password-reset/confirm/', PasswordResetConfirmView.as_view(), name='password-reset-confirm'),
    path('delete-account/request/', DeleteAccountRequestView.as_view(), name='delete-account-request'),
    path('delete-account/confirm/', DeleteAccountConfirmView.as_view(), name='delete-account-confirm'),
    path('password-change/', PasswordChangeView.as_view(), name='password-change'),
    path('me/', ProfileView.as_view(), name='profile'),
    path('users/<int:user_id>/', PublicProfileView.as_view(), name='public-profile'),
    path('users/search/', UserSearchView.as_view(), name='users-search'),
    path('friends/', FriendsListView.as_view(), name='friends-list'),
    path('friends/request/', FriendRequestCreateView.as_view(), name='friend-request-create'),
    path('friends/requests/incoming/', FriendRequestsIncomingView.as_view(), name='friend-requests-incoming'),
    path('friends/requests/<int:request_id>/accept/', FriendRequestAcceptView.as_view(), name='friend-request-accept'),
    path('friends/requests/<int:request_id>/decline/', FriendRequestDeclineView.as_view(), name='friend-request-decline'),
    path('notifications/', NotificationsListView.as_view(), name='notifications-list'),
    path('notifications/read-all/', NotificationMarkAllReadView.as_view(), name='notifications-read-all'),
    path('notifications/<int:notification_id>/read/', NotificationMarkReadView.as_view(), name='notifications-read'),
    path('chats/', ChatDialogsView.as_view(), name='chat-dialogs'),
    path('chats/<int:user_id>/messages/', ChatMessagesView.as_view(), name='chat-messages'),
    path('permissions/inviters/', AllowedInvitersView.as_view(), name='allowed-inviters'),
    path('telegram/link-code/', TelegramLinkCodeView.as_view(), name='telegram-link-code'),
    path('telegram/toggle/', TelegramNotificationsToggleView.as_view(), name='telegram-toggle'),
    path('telegram/link-callback/', telegram_link_callback, name='telegram-link-callback'),
]
