# Generated by Django 5.1.6 on 2026-02-21 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_steam_profile_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailactiontoken',
            name='action',
            field=models.CharField(choices=[('verify_email', 'Verify email'), ('reset_password', 'Reset password'), ('telegram_link', 'Telegram link'), ('delete_account', 'Delete account')], max_length=32),
        ),
    ]
