# Generated by Django 5.1.6 on 2026-02-22 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_pending_email_user_pending_email_expires_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='ws_connection_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
